### ISSUE TITLE
A detailed result about 100-5

### ISSUE THREAD

**Issue by adaxidedakaonang** [schuy1er/EWF_official#1]
Hi, thank you for offering the code, I want to know if it's convenient for you to provide the result of each step for the 100-5?

**Comment by schuy1er** [comment]
Yes, of course.
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">


</head>
<body>



0 | 0.35832232 | 0.6754685 | 0.7455685 | 0.9165518 | 0.71686584 | 0.6823581 | 0.7547273 | 0.77612835 | 0.7363776 | 0.57118887 | 0.6099107 | 0.5215015 | 0.5528771 | 0.7136639 | 0.2612571 | 0.3326385 | 0.44270223 | 0.54296565 | 0.38512063 | 0.6332661 | 0.47899547 | 0.76474935 | 0.46283475 | 0.5942721 | 0.5408827 | 0.3822523 | 0.36841407 | 0.6888503 | 0.49272975 | 0.48215613 | 0.33362612 | 0.31749105 | 0.49739605 | 0.29455617 | 0.38908806 | 0.34291753 | 0.40706944 | 0.4590554 | 0.5913763 | 0.22664985 | 0.44830146 | 0.0591352 | 0.12995584 | 0.34143603 | 0.2536642 | 0.38764253 | 0.21531741 | 0.355366 | 0.5459416 | 0.484068 | 0.570765 | 0.58350223 | 0.2935985 | 0.14385274 | 0.25410527 | 0.52812666 | 0.5031204 | 0.87350374 | 0.46606693 | 0.48335168 | 0.3078211 | 0.2760212 | 0.40071803 | 0.38138494 | 0.3315386 | 0.4742851 | 0.69884366 | 0.36322635 | 0.32891893 | 0.15052411 | 0.36646855 | 0.49417877 | 0.57594585 | 0.5218035 | 0.26339537 | 0.49742848 | 0.36372498 | 0.29892033 | 0.25236097 | 0.15159959 | 0.30843392 | 0.7297769 | 0.42358425 | 0.34264642 | 0.05382204 | 0.30521247 | 0.5513219 | 0.15737732 | 0.15327004 | 0.19368838 | 0.67517847 | 0.42561388 | 0.18064389 | 0.22208844 | 0.103693336 | 0.00152583 | 0.05363204 | 0.22687232 | 0.35389724 | 0.16923316 | 0.31336626 | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | 0.419897318
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 0.35296854 | 0.6734005 | 0.74609494 | 0.91622776 | 0.71530163 | 0.68183154 | 0.7536154 | 0.77530783 | 0.73656064 | 0.57144314 | 0.609063 | 0.5220463 | 0.5505986 | 0.7126938 | 0.26701635 | 0.33152896 | 0.44338125 | 0.5390886 | 0.3864499 | 0.63346565 | 0.4792536 | 0.76406866 | 0.46780133 | 0.59015226 | 0.54133254 | 0.38252735 | 0.37544882 | 0.68929064 | 0.4954057 | 0.48073623 | 0.3365157 | 0.31882697 | 0.5009537 | 0.28747264 | 0.39050436 | 0.34664702 | 0.4051914 | 0.4564498 | 0.59025425 | 0.22716245 | 0.44630018 | 0.061458364 | 0.13293323 | 0.3400589 | 0.25513524 | 0.38847634 | 0.21905689 | 0.3622189 | 0.5384844 | 0.48050088 | 0.57382447 | 0.58578056 | 0.29485095 | 0.14540762 | 0.25593683 | 0.5291666 | 0.5071355 | 0.8706358 | 0.46208483 | 0.48739633 | 0.3091198 | 0.27491897 | 0.40452537 | 0.38073885 | 0.33278665 | 0.4776753 | 0.6934725 | 0.3712685 | 0.32846805 | 0.14468138 | 0.3637467 | 0.49609795 | 0.584692 | 0.5197232 | 0.26313382 | 0.50501275 | 0.36646214 | 0.30485678 | 0.24985729 | 0.1728484 | 0.31717452 | 0.7282073 | 0.42466867 | 0.34747964 | 0.057835966 | 0.29916316 | 0.55318296 | 0.1595121 | 0.15685013 | 0.20517908 | 0.68281597 | 0.3834761 | 0.17374888 | 0.2114849 | 0.105155885 | 0.001337731 | 0.053797234 | 0.22937922 | 0.35118642 | 0.1739611 | 0.31907555 | 0.00651395 | 0.000105766 | 0.11236571 | 0 | 0 | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | 0.401685536
2 | 0.3387118 | 0.67234546 | 0.74321824 | 0.9153178 | 0.71303815 | 0.68025184 | 0.752196 | 0.7754075 | 0.736938 | 0.5704908 | 0.60883635 | 0.5208111 | 0.5487818 | 0.7104063 | 0.27226487 | 0.32919964 | 0.44158494 | 0.5394964 | 0.38596928 | 0.6329402 | 0.47821528 | 0.7610211 | 0.47744498 | 0.58594143 | 0.54117066 | 0.3826869 | 0.37585798 | 0.6884968 | 0.497168 | 0.4736508 | 0.33702824 | 0.31844914 | 0.50153965 | 0.2883593 | 0.39532894 | 0.3450804 | 0.4050433 | 0.45341218 | 0.5856727 | 0.22450437 | 0.4472036 | 0.06647926 | 0.13762677 | 0.34704372 | 0.25449342 | 0.3893983 | 0.22102068 | 0.36077315 | 0.53315043 | 0.48652086 | 0.5764091 | 0.58466566 | 0.28805426 | 0.1497886 | 0.25503048 | 0.52890235 | 0.51045007 | 0.8688681 | 0.45901477 | 0.492307 | 0.3092084 | 0.28592628 | 0.3992947 | 0.38076112 | 0.33778337 | 0.47718647 | 0.69082236 | 0.3643511 | 0.32531515 | 0.14377344 | 0.36892888 | 0.49546626 | 0.5918934 | 0.5141224 | 0.2601419 | 0.5134538 | 0.36568794 | 0.3140247 | 0.2631517 | 0.19482397 | 0.3469101 | 0.720959 | 0.42836076 | 0.34997973 | 0.062130686 | 0.29727277 | 0.5537611 | 0.14702864 | 0.16236474 | 0.21797487 | 0.6810314 | 0.36345002 | 0.17037328 | 0.19994673 | 0.10853803 | 0.000642543 | 0.057005003 | 0.2442628 | 0.35526818 | 0.17302577 | 0.33701423 | 0.03235247 | 0.001919704 | 0.20124228 | 0 | 0.000218891 | 0 | 0.026089557 | 0.006139426 | 0.00268109 | 0.015508413 | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | 0.385775179
3 | 0.31815 | 0.6704357 | 0.74015456 | 0.91445583 | 0.71176684 | 0.67914164 | 0.7519378 | 0.77433014 | 0.7365486 | 0.5683757 | 0.60969394 | 0.5204294 | 0.54679286 | 0.70765775 | 0.27706367 | 0.32728454 | 0.4406139 | 0.53974736 | 0.3881503 | 0.6321582 | 0.4776162 | 0.7588889 | 0.4773241 | 0.5803149 | 0.5387619 | 0.38031933 | 0.37714833 | 0.68540496 | 0.49561387 | 0.47465715 | 0.34144568 | 0.31953827 | 0.5023811 | 0.28179973 | 0.39331928 | 0.35017672 | 0.4034921 | 0.45193508 | 0.58782405 | 0.22284678 | 0.4472809 | 0.07132584 | 0.13951138 | 0.3539749 | 0.25301838 | 0.39026406 | 0.22212304 | 0.3602833 | 0.52989095 | 0.48777807 | 0.5795601 | 0.58256066 | 0.28466055 | 0.14997776 | 0.2546985 | 0.5256477 | 0.5059209 | 0.8661031 | 0.4587968 | 0.49354672 | 0.3093564 | 0.29618126 | 0.39364603 | 0.38174215 | 0.3387658 | 0.47756085 | 0.690323 | 0.35888925 | 0.32033637 | 0.14174086 | 0.36924207 | 0.4954858 | 0.5949786 | 0.5122073 | 0.26106557 | 0.51473176 | 0.36471564 | 0.33650783 | 0.264768 | 0.22750014 | 0.36000073 | 0.7150042 | 0.4309106 | 0.35201347 | 0.06554938 | 0.29170057 | 0.5554293 | 0.13976339 | 0.16212429 | 0.22394916 | 0.6775021 | 0.33440742 | 0.17300297 | 0.1958078 | 0.11288152 | 0.00028014 | 0.056867857 | 0.25396028 | 0.35660774 | 0.17601228 | 0.33403596 | 0.06813788 | 0.009263495 | 0.24852583 | 0 | 0.000720546 | 0.024792073 | 0.039169442 | 0.031118501 | 0.027953446 | 0.103420556 | 0.14930923 | 0 | 0.022790607 | 0.48420757 | 0.09850118 | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | 0.377914518
4 | 0.29025647 | 0.6677575 | 0.7394729 | 0.9139023 | 0.70974183 | 0.6772998 | 0.7500011 | 0.77392614 | 0.73648053 | 0.566324 | 0.60728204 | 0.51883465 | 0.54586273 | 0.704223 | 0.28006834 | 0.3273169 | 0.44086602 | 0.5355846 | 0.3877969 | 0.63200754 | 0.47607085 | 0.75777644 | 0.4750452 | 0.5755639 | 0.5389305 | 0.37643173 | 0.3794982 | 0.68427384 | 0.49574313 | 0.47371295 | 0.33830494 | 0.31874517 | 0.50250864 | 0.27490693 | 0.3860558 | 0.34792045 | 0.40313125 | 0.4496559 | 0.5886036 | 0.22009349 | 0.44624656 | 0.076307565 | 0.13879107 | 0.3532891 | 0.25268993 | 0.3902135 | 0.2187284 | 0.37011486 | 0.5232713 | 0.48619556 | 0.58116657 | 0.5808082 | 0.28666073 | 0.14706846 | 0.25520846 | 0.5226404 | 0.4991473 | 0.86139125 | 0.45778504 | 0.4950625 | 0.30850434 | 0.2957739 | 0.38970774 | 0.38207167 | 0.34054562 | 0.47480398 | 0.68366337 | 0.36049467 | 0.31799033 | 0.1427129 | 0.36724183 | 0.4952363 | 0.59504735 | 0.5079356 | 0.25938088 | 0.5132832 | 0.36736506 | 0.35293627 | 0.26320016 | 0.24824171 | 0.35402074 | 0.709572 | 0.43217507 | 0.35313076 | 0.06433726 | 0.28081802 | 0.55543315 | 0.13743918 | 0.16155054 | 0.22897722 | 0.6656621 | 0.3146193 | 0.1731523 | 0.18206595 | 0.112560846 | 0.000247986 | 0.055680986 | 0.25294602 | 0.3600166 | 0.17850702 | 0.3354824 | 0.09169286 | 0.019500444 | 0.252081 | 0 | 0.001720682 | 0.09333428 | 0.032615215 | 0.11997502 | 0.026881613 | 0.12539177 | 0.17845047 | 0 | 0.040880468 | 0.4499217 | 0.3300731 | 0.000603684 | 0.2268496 | 0.42143688 | 0.234148 | 0.023683034 | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | 0.372351527
5 | 0.23277137 | 0.66559505 | 0.7388133 | 0.9130372 | 0.7072879 | 0.67473775 | 0.74828094 | 0.7740895 | 0.73558354 | 0.5655253 | 0.603071 | 0.5182342 | 0.5443017 | 0.6996893 | 0.28304908 | 0.32913736 | 0.4405265 | 0.531564 | 0.38801047 | 0.628132 | 0.47466192 | 0.7572683 | 0.4747655 | 0.56818527 | 0.53762215 | 0.37162995 | 0.37835598 | 0.68056434 | 0.49774304 | 0.4751189 | 0.33236185 | 0.31926122 | 0.5046201 | 0.26772115 | 0.38050857 | 0.34532806 | 0.4029773 | 0.4470095 | 0.59245133 | 0.22004226 | 0.44673464 | 0.07803151 | 0.1372613 | 0.3526677 | 0.253093 | 0.3889334 | 0.22230779 | 0.39234576 | 0.51744103 | 0.48481262 | 0.58247495 | 0.579254 | 0.28485245 | 0.14526637 | 0.25547937 | 0.51864207 | 0.50262284 | 0.85743713 | 0.45705375 | 0.5044451 | 0.30448663 | 0.28917593 | 0.38672736 | 0.38073385 | 0.33951706 | 0.4753604 | 0.6788456 | 0.36380643 | 0.3176629 | 0.14176157 | 0.3635993 | 0.49306354 | 0.5966052 | 0.5051177 | 0.25953358 | 0.51128817 | 0.36801925 | 0.36489046 | 0.25917685 | 0.27669957 | 0.3504393 | 0.70859945 | 0.4274791 | 0.3534649 | 0.063455164 | 0.27407628 | 0.5583903 | 0.13719073 | 0.16186494 | 0.23273425 | 0.6533695 | 0.30004618 | 0.17369565 | 0.17149295 | 0.109233946 | 0.000270492 | 0.055390168 | 0.2500102 | 0.36253363 | 0.18133743 | 0.33989304 | 0.08503461 | 0.027472539 | 0.23185205 | 0.004071957 | 0.014386439 | 0.104024656 | 0.020205498 | 0.26434144 | 0.020372141 | 0.093729556 | 0.16586588 | 0 | 0.07691971 | 0.36683112 | 0.38916063 | 0.016259361 | 0.30894598 | 0.6474178 | 0.23478216 | 0.14152606 | 0.3048062 | 0.034750234 | 0.02367591 | 0.17697316 | 0.30268574 | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | 0.367523134
6 | 0.17143096 | 0.66371566 | 0.7384539 | 0.91262317 | 0.705639 | 0.67341584 | 0.7464071 | 0.7741135 | 0.7354524 | 0.5638227 | 0.6012918 | 0.5164006 | 0.5439912 | 0.6962747 | 0.28671205 | 0.3305074 | 0.4393742 | 0.5270306 | 0.38915095 | 0.6289629 | 0.47346228 | 0.75715566 | 0.47949734 | 0.5649251 | 0.5365288 | 0.36953345 | 0.37851247 | 0.6789924 | 0.4988014 | 0.47484097 | 0.33664125 | 0.3203061 | 0.50362813 | 0.2639424 | 0.3766967 | 0.34402764 | 0.40058976 | 0.44561175 | 0.59283155 | 0.2179111 | 0.44532412 | 0.07964069 | 0.13557671 | 0.35536656 | 0.25202253 | 0.3902973 | 0.22341387 | 0.38946298 | 0.5098642 | 0.48538196 | 0.5830221 | 0.5769223 | 0.28305936 | 0.14700077 | 0.2557128 | 0.513516 | 0.5011386 | 0.85175234 | 0.45653415 | 0.5092874 | 0.3053812 | 0.30448434 | 0.38282767 | 0.3810394 | 0.33879384 | 0.47374347 | 0.6747713 | 0.3652298 | 0.31622407 | 0.1403018 | 0.36171407 | 0.4898327 | 0.5958117 | 0.5039075 | 0.2585983 | 0.5094974 | 0.36979213 | 0.36377543 | 0.2577242 | 0.31271878 | 0.35045898 | 0.7061689 | 0.4270371 | 0.35270923 | 0.061722588 | 0.26857734 | 0.558966 | 0.13658682 | 0.16219921 | 0.24851412 | 0.6448588 | 0.29256153 | 0.16534054 | 0.16537048 | 0.108989775 | 0.000344516 | 0.05437501 | 0.25359824 | 0.35740498 | 0.18182911 | 0.34287924 | 0.07319339 | 0.025340103 | 0.20683269 | 0.104542494 | 0.024231168 | 0.06274324 | 0.013838082 | 0.44085482 | 0.01759383 | 0.0785586 | 0.14037792 | 0 | 0.10809751 | 0.32158086 | 0.34899318 | 0.04521551 | 0.25117725 | 0.60427004 | 0.21213011 | 0.19892643 | 0.31263277 | 0.034050234 | 0.06633837 | 0.18060033 | 0.32038477 | 0.19437131 | 0.3625468 | 0.2350126 | 0.11366074 | 0.4336075 | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | 0.36398375
7 | 0.095033124 | 0.6634148 | 0.7357571 | 0.9122946 | 0.70580655 | 0.67304784 | 0.7468189 | 0.77344525 | 0.73564285 | 0.5623115 | 0.60484743 | 0.5155783 | 0.5441144 | 0.6944178 | 0.28843072 | 0.3317311 | 0.43858063 | 0.52859914 | 0.3893606 | 0.6308792 | 0.47285178 | 0.75688475 | 0.4789569 | 0.56238955 | 0.5367942 | 0.36545318 | 0.38328612 | 0.67827183 | 0.49721926 | 0.47493118 | 0.3421075 | 0.3204924 | 0.5046475 | 0.26213974 | 0.37450194 | 0.3499417 | 0.398202 | 0.4476493 | 0.5911719 | 0.21586427 | 0.4466763 | 0.08443347 | 0.13477914 | 0.35923856 | 0.25110012 | 0.39208296 | 0.22304486 | 0.3876028 | 0.5061235 | 0.4866991 | 0.58083814 | 0.57257766 | 0.27703032 | 0.14746894 | 0.25366834 | 0.5116684 | 0.4999209 | 0.84963745 | 0.45772177 | 0.51775986 | 0.30209658 | 0.3025934 | 0.37708035 | 0.3773745 | 0.33640108 | 0.47333425 | 0.6739323 | 0.36471686 | 0.31591254 | 0.13594353 | 0.3599314 | 0.4883581 | 0.5978487 | 0.50126994 | 0.25435972 | 0.5049967 | 0.37085924 | 0.35700384 | 0.2596449 | 0.357253 | 0.35706005 | 0.70020294 | 0.425928 | 0.35396263 | 0.065161526 | 0.26968127 | 0.5612809 | 0.13199906 | 0.16230069 | 0.25588784 | 0.646094 | 0.2828211 | 0.16473615 | 0.16636656 | 0.109222144 | 0.000252467 | 0.054984793 | 0.25951946 | 0.3568682 | 0.18062223 | 0.33909774 | 0.07019799 | 0.021944504 | 0.17339388 | 0.10541726 | 0.02319016 | 0.042760074 | 0.011955424 | 0.48622948 | 0.01611445 | 0.06697595 | 0.11037943 | 0.029177645 | 0.10945636 | 0.29007617 | 0.2631881 | 0.044702597 | 0.19213597 | 0.49646688 | 0.14624229 | 0.18073599 | 0.28264353 | 0.03086497 | 0.062393002 | 0.17129321 | 0.3182079 | 0.19046539 | 0.34317535 | 0.25726888 | 0.12559031 | 0.43910062 | 0.32720256 | 0.04079005 | 0.05599737 | 0.36102608 | 0.09956762 | x | x | x | x | x | x | x | x | x | x | x | x | x | x | x | 0.353420824
8 | 0.033102017 | 0.6627922 | 0.73536605 | 0.91204345 | 0.70491815 | 0.6725197 | 0.7463021 | 0.77382094 | 0.7350097 | 0.56153995 | 0.60500234 | 0.5143276 | 0.5434228 | 0.69296443 | 0.28733414 | 0.33054334 | 0.4378462 | 0.5266118 | 0.3894397 | 0.6309506 | 0.47251853 | 0.7566069 | 0.47716206 | 0.5594277 | 0.5360353 | 0.36469296 | 0.38269117 | 0.67670065 | 0.49750784 | 0.47394362 | 0.34396887 | 0.32107216 | 0.502239 | 0.2614672 | 0.37395236 | 0.34925178 | 0.39552757 | 0.4477552 | 0.5903689 | 0.21521199 | 0.44532463 | 0.08501413 | 0.13343926 | 0.36068937 | 0.25179195 | 0.39270595 | 0.2236572 | 0.3926016 | 0.5039179 | 0.48508537 | 0.5813199 | 0.5717278 | 0.2722256 | 0.14968845 | 0.25374708 | 0.51047456 | 0.4995244 | 0.845811 | 0.4570125 | 0.51739216 | 0.30100808 | 0.3016702 | 0.3759513 | 0.37449014 | 0.3373661 | 0.47173795 | 0.6724834 | 0.36800247 | 0.31891453 | 0.13472153 | 0.3597958 | 0.4856263 | 0.5984517 | 0.49867076 | 0.2524811 | 0.502261 | 0.37186912 | 0.35570478 | 0.2565373 | 0.36597165 | 0.35816783 | 0.6987206 | 0.4245946 | 0.35425228 | 0.06689976 | 0.26861116 | 0.56193006 | 0.13364002 | 0.16246653 | 0.26632962 | 0.6446966 | 0.27947164 | 0.16180037 | 0.16754355 | 0.108816706 | 0.000264744 | 0.054351296 | 0.26108873 | 0.3550094 | 0.18142597 | 0.33909738 | 0.06620884 | 0.018421875 | 0.15324628 | 0.09226727 | 0.019991625 | 0.035110354 | 0.01031348 | 0.41035834 | 0.015820704 | 0.06075056 | 0.09550157 | 0.10044913 | 0.101796836 | 0.279897 | 0.20497215 | 0.03984273 | 0.16400878 | 0.43438983 | 0.11471149 | 0.17075606 | 0.24052243 | 0.024431929 | 0.05920508 | 0.16883002 | 0.31258583 | 0.1922189 | 0.29697594 | 0.24518244 | 0.12118013 | 0.43584272 | 0.29891494 | 0.038703933 | 0.04758506 | 0.34869528 | 0.09591182 | 0.07185955 | 0.06512546 | 0.000163868 | 0.062204372 | 0.20068596 | x | x | x | x | x | x | x | x | x | x | 0.33968544
9 | 0.001877638 | 0.66225815 | 0.73434085 | 0.9117069 | 0.704321 | 0.6707828 | 0.74732643 | 0.7735424 | 0.7340372 | 0.5615466 | 0.6045759 | 0.51427174 | 0.5419491 | 0.6934929 | 0.28695682 | 0.33146656 | 0.43886384 | 0.5259409 | 0.3891167 | 0.62845266 | 0.47274512 | 0.75453025 | 0.4762833 | 0.56041193 | 0.53567165 | 0.3641725 | 0.38175318 | 0.67404324 | 0.49580657 | 0.47143295 | 0.3405055 | 0.32055008 | 0.5015395 | 0.26191318 | 0.3717907 | 0.34612137 | 0.39491707 | 0.44724116 | 0.5889986 | 0.2151478 | 0.44422024 | 0.08567631 | 0.13336985 | 0.36179549 | 0.25133696 | 0.39436957 | 0.2232246 | 0.40067562 | 0.5030531 | 0.48234493 | 0.58074397 | 0.5713752 | 0.26920968 | 0.15019977 | 0.25270152 | 0.5129221 | 0.50093895 | 0.8446988 | 0.45596913 | 0.51679355 | 0.29725593 | 0.30186015 | 0.38212436 | 0.37302628 | 0.33578977 | 0.47192362 | 0.674503 | 0.3653548 | 0.32004058 | 0.13344087 | 0.3573162 | 0.48735562 | 0.5992887 | 0.49680725 | 0.24904594 | 0.50471413 | 0.37075418 | 0.3471014 | 0.25664708 | 0.35433954 | 0.3660262 | 0.6953356 | 0.42043594 | 0.35456297 | 0.0642383 | 0.27345103 | 0.5617886 | 0.12976359 | 0.15941009 | 0.24548553 | 0.6429622 | 0.27489117 | 0.15896954 | 0.16449586 | 0.10855454 | 0.000242254 | 0.05465932 | 0.25984454 | 0.3576991 | 0.17934634 | 0.33645555 | 0.07022579 | 0.017363034 | 0.14757329 | 0.101775005 | 0.020027509 | 0.036053676 | 0.009562931 | 0.36577004 | 0.015967144 | 0.05590483 | 0.095475726 | 0.09063819 | 0.09793627 | 0.27441633 | 0.19357543 | 0.0341153 | 0.15910953 | 0.3898171 | 0.11223494 | 0.16053362 | 0.23489478 | 0.022974426 | 0.057035692 | 0.16760772 | 0.3173425 | 0.1940502 | 0.27448657 | 0.24410783 | 0.108355865 | 0.41850016 | 0.34973815 | 0.03585433 | 0.04521447 | 0.3386847 | 0.0918571 | 0.06345917 | 0.06421722 | 0.008300185 | 0.057889465 | 0.18816844 | 0.04337082 | 0.06337745 | 0.23070553 | 0.073657274 | 0.09403504 | x | x | x | x | x | 0.329392374
10 | 2.60E-05 | 0.6620351 | 0.73468953 | 0.9118274 | 0.7047284 | 0.6717297 | 0.7474703 | 0.7732325 | 0.7342763 | 0.5608132 | 0.60388225 | 0.51347923 | 0.54139054 | 0.692719 | 0.28766036 | 0.33018956 | 0.438878 | 0.5264224 | 0.38874626 | 0.62702596 | 0.4724508 | 0.75433725 | 0.4733948 | 0.55873895 | 0.53538746 | 0.36387143 | 0.38384694 | 0.67396754 | 0.49632353 | 0.47254717 | 0.3398229 | 0.3221651 | 0.49967307 | 0.263646 | 0.37095925 | 0.34490734 | 0.3951946 | 0.44576034 | 0.5848546 | 0.21638718 | 0.44423065 | 0.08609932 | 0.13302864 | 0.36059535 | 0.2509344 | 0.3933715 | 0.22409132 | 0.4069783 | 0.5010727 | 0.48426846 | 0.5814242 | 0.57018393 | 0.2657767 | 0.14987366 | 0.25301152 | 0.5127842 | 0.49947715 | 0.8431068 | 0.45626518 | 0.5185297 | 0.29609436 | 0.29951423 | 0.38102478 | 0.3717571 | 0.33702004 | 0.4722273 | 0.6712846 | 0.36293593 | 0.32319513 | 0.1309978 | 0.35663158 | 0.48765865 | 0.59841573 | 0.49474907 | 0.24750035 | 0.50332606 | 0.3722928 | 0.3503653 | 0.2594773 | 0.3586756 | 0.3631004 | 0.6953642 | 0.4196608 | 0.3548938 | 0.064756624 | 0.26977912 | 0.56341577 | 0.12988013 | 0.16081192 | 0.25103292 | 0.6363343 | 0.27421692 | 0.1542985 | 0.16383748 | 0.10888848 | 0.000218371 | 0.053154506 | 0.26037866 | 0.35643396 | 0.18004902 | 0.3404876 | 0.07153041 | 0.017659402 | 0.14470011 | 0.10760936 | 0.023570355 | 0.03700182 | 0.009836524 | 0.36783037 | 0.016028082 | 0.05585566 | 0.09470788 | 0.09083094 | 0.099086456 | 0.27865317 | 0.1987351 | 0.029963885 | 0.15778026 | 0.4111146 | 0.110758945 | 0.16199361 | 0.23161007 | 0.024949912 | 0.06147806 | 0.16546728 | 0.3164309 | 0.19490354 | 0.27740687 | 0.2424538 | 0.11001147 | 0.4141392 | 0.347831 | 0.038836725 | 0.043913763 | 0.33491635 | 0.09145771 | 0.06631882 | 0.067950375 | 0.014483233 | 0.055762514 | 0.18367042 | 0.042472713 | 0.060509905 | 0.24159148 | 0.07711575 | 0.09878232 | 0 | 0.25472513 | 0 | 0.033560567 | 0.106226355 | 0.32129088
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  



</body>

</html>

**Comment by adaxidedakaonang** [comment]
Thank you very much !
