### ISSUE TITLE
Reported results in the paper.

### ISSUE THREAD

**Issue by adaxidedakaonang** [schuy1er/EWF_official#2]
Seems your test results are based on the cropped test images. I run the 15-1 setting, and the mIoU should be the 62% instead of 67%. I think by default we should not use the cropped test images for final test.

**Comment by schuy1er** [comment]
Thanks for the question. 
It's mainly for the convenience of comparison with the previous work. PLOP, MiB, and RCIL all use cropping of the test image, and we continue to adopt this. It should be noted that the new codebases "ALIFE" and "AWT" currently adopt this as well.
