### ISSUE TITLE
Fixed pre_cls_weight

### ISSUE THREAD

**Issue by jainie-max** [schuy1er/EWF_official#3]
Hi！ Thanks for your great work, I have a small question about the fixed pre_cls classifier weight. Why the weight of pre_cls in the classifier need fixed during the current step?

**Comment by schuy1er** [comment]
Hi! Thanks for your question. The main reason is that fixing it will enhance the stability of the method. This is equivalent to adjusting the learning rate on the classifiers. I mentioned this step in the implementation details in the supplementary material.
