### ISSUE TITLE
Environment setup problem

### ISSUE THREAD

**Issue by James-FE** [schuy1er/EWF_official#4]
Thank you for your contribution, but I meet lots of troubles when I want to reproduce your project and I really need some help. Here are some issues I met.
1. I tried set up the environment with the yaml file, but the mirror source ustc link is already closed and there are two packages "  - pytorch=1.3.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - torchvision=0.4.2=py36_cu101" were already obsoleted by Anaconda.  I couldn't find them anywhere, is it possible for you to upload those two packages on github?
 
2. the project need to use inplace-abn package, I found it is incompatible with python 3.6. It need at least python 3.7(pip told me). I wonder the environment.yaml file is correct or not, could you please check it? Thank you very much!

**Comment by schuy1er** [comment]
Hi, thanks for your question.
Since this environment may be difficult to configure now, you can try the environment provided by PLOP first, which may cause some performance differences, but it will not cause a big impact.
