### ISSUE TITLE
A detailed result about 15-1, 10-1, 5-3, 19-1

### ISSUE THREAD

**Issue by TAEWOOGWAK** [schuy1er/EWF_official#6]
Hi, thank you for your contribution. I want to know the results of each step for 15-1, 10-1, 5-3, 19-1.
Could you provide that?

**Comment by schuy1er** [comment]
Hi, sorry for the late update. However, since so much time has passed, it is really hard for me to find the detailed results of each step. Maybe the most convenient way is to reproduce it directly.
